### PR TITLE
Added "about this open-source project" to announce that the

### PR DESCRIPTION
**Pull request by nassol**
communication will be done in English and the feedback can be given.

### CODE REVIEW

**Comment by nassol** [comment]
Added a new file of FEATURES.md. This will be moved to a Wiki doc later on.

**Comment by nassol** [comment]
Pull request successfully merged and closed
You're all set—the nassol:develop branch can be safely deleted.   <- I see this message..

The nassol:develop branch can be deleted? What does it mean? why would I delete my branch? Because I can directly push into leehosung:develop branch?

**Comment by leehosung** [comment]
Did I delete  your nassol:develop branch? sorry. I don't remeber it. 
Can you send me an another pull request? I will try to test it.

**Comment by nassol** [comment]
@leehosung Nono, you didn't delete my branch! 

The message I saw is as below:

Pull request successfully merged and closed  
You're all set—the nassol:develop branch can be safely deleted.

**Pull request merged**
